<%@ page contentType="text/html" pageEncoding="UTF-8" %>
<%@ page import = "java.sql.*" %>

<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Database SQL Load</title>
    </head>
    <style>
        .error {
            color: red;
        }
        pre {
            color: green;
        }
    </style>
    <body>
        <h2>Database SQL Load</h2>
        <%
            /* How to customize:
             * 1. Update the database name on dbname.
             * 2. Create the list of tables, under tablenames[].
             * 3. Create the list of table definition, under tables[].
             * 4. Create the data into the above table, under data[]. 
             * 
             * If there is any problem, it will exit at the very first error.
             */
            String dbname = "homework1";
            String schema = "ROOT";
            Class.forName("org.apache.derby.jdbc.ClientDriver");
            /* this will generate database if not exist */
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/" + dbname, "root", "root");
            Statement stmt = con.createStatement();

            /* inserting data */
 /* you have to exclude the id autogenerated from the list of columns if you have use it. */
String data[] = new String[]{
    "INSERT INTO Game (id, price, name, type, console, stock, pathImage) VALUES (300, 35, 'Final Fantasy VII', 'RPG', 'PlayStation', 15, '/Homework2/resources/img/videogame1.PNG')",
    "INSERT INTO Game (id, price, name, type, console, stock, pathImage) VALUES (400, 35, 'The Elder Scrolls V: Skyrim', 'Action RPG', 'Xbox', 1, '/Homework2/resources/img/videogame1.PNG')",
    "INSERT INTO Game (id, price, name, type, console, stock, pathImage) VALUES (500, 35, 'Grand Theft Auto V', 'Action-Adventure', 'PlayStation', 12, '/Homework2/resources/img/videogame1.PNG')",
    "INSERT INTO Game (id, price, name, type, console, stock, pathImage) VALUES (600, 35, 'Minecraft', 'Sandbox', 'PC', 20, '/Homework2/resources/img/videogame1.PNG')",
    "INSERT INTO Game (id, price, name, type, console, stock, pathImage) VALUES (700, 35, 'Red Dead Redemption 2', 'Action-Adventure', 'Xbox', 10, '/Homework2/resources/img/videogame1.PNG')",
    "INSERT INTO Game (id, price, name, type, console, stock, pathImage) VALUES (800, 35, 'The Witcher 3: Wild Hunt', 'Action RPG', 'PlayStation', 18, '/Homework2/resources/img/videogame1.PNG')",
    "INSERT INTO Game (id, price, name, type, console, stock, pathImage) VALUES (900, 35, 'Super Smash Bros. Ultimate', 'Fighting', 'Nintendo Switch', 14, '/Homework2/resources/img/videogame1.PNG')",
    "INSERT INTO Game (id, price, name, type, console, stock, pathImage) VALUES (1000, 35, 'Fortnite', 'Battle Royale', 'PC', 25, '/Homework2/resources/img/videogame1.PNG')",
    "INSERT INTO Game (id, price, name, type, console, stock, pathImage) VALUES (1100, 35, 'Call of Duty: Warzone', 'Battle Royale', 'Xbox', 8, '/Homework2/resources/img/videogame1.PNG')",
    "INSERT INTO Game (id, price, name, type, console, stock, pathImage) VALUES (1200, 35, 'Overwatch', 'FPS', 'PlayStation', 15, '/Homework2/resources/img/videogame1.PNG')",
    "INSERT INTO Game (id, price, name, type, console, stock, pathImage) VALUES (1300, 35, 'Animal Crossing: New Horizons', 'Life Simulation', 'Nintendo Switch', 20, '/Homework2/resources/img/videogame1.PNG')",
    "INSERT INTO Game (id, price, name, type, console, stock, pathImage) VALUES (1400, 35, 'FIFA 22', 'Sports', 'Xbox', 12, '/Homework2/resources/img/videogame1.PNG')",
    "INSERT INTO Game (id, price, name, type, console, stock, pathImage) VALUES (1500, 35, 'Assassins Creed Valhalla', 'Action RPG', 'PlayStation', 10, '/Homework2/resources/img/videogame1.PNG')",
    "INSERT INTO Game (id, price, name, type, console, stock, pathImage) VALUES (1600, 35, 'Cyberpunk 2077', 'Action RPG', 'PC', 15, '/Homework2/resources/img/videogame1.PNG')",
    "INSERT INTO Game (id, price, name, type, console, stock, pathImage) VALUES (1700, 35, 'Splatoon 2', 'Third-Person Shooter', 'Nintendo Switch', 18, '/Homework2/resources/img/videogame1.PNG')",
    "INSERT INTO Game (id, price, name, type, console, stock, pathImage) VALUES (1800, 35, 'Star Wars Jedi: Fallen Order', 'Action-Adventure', 'Xbox', 10, '/Homework2/resources/img/videogame1.PNG')",
    "INSERT INTO Game (id, price, name, type, console, stock, pathImage) VALUES (1900, 35, 'Doom Eternal', 'First-Person Shooter', 'PlayStation', 12, '/Homework2/resources/img/videogame1.PNG')",
    "INSERT INTO Game (id, price, name, type, console, stock, pathImage) VALUES (2000, 35, 'Among Us', 'Social Deduction', 'PC', 15, '/Homework2/resources/img/videogame1.PNG')",
    "INSERT INTO Game (id, price, name, type, console, stock, pathImage) VALUES (2100, 35, 'Rocket League', 'Sports', 'Nintendo Switch', 20, '/Homework2/resources/img/videogame1.PNG')",
    "INSERT INTO Game (id, price, name, type, console, stock, pathImage) VALUES (2200, 35, 'Halo Infinite', 'First-Person Shooter', 'Xbox', 10, '/Homework2/resources/img/videogame1.PNG')"
};


            for (String datum : data) {
                if (stmt.executeUpdate(datum) <= 0) {
                    out.println("<span class='error'>Error inserting data: " + datum + "</span>");
                    return;
                }
                out.println("<pre> -> " + datum + "<pre>");
            }
        %>
        <button onclick="window.location = '<%=request.getSession().getServletContext().getContextPath()%>'">Go home</button>
    </body>
</html>
